openapi: 3.0.0
info:
  title: FPPSS-Energy REST-API
  description: FPPSS-Energy REST-API
  version: 1.0.0
tags:
  - name: developers
    description: Operations available to regular developers
paths:
  /provideraccounts:
    get:
      tags:
        - developers
      description: get all provider accounts
      operationId: provideraccounts
      responses:
        "200":
          description: successfully query
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProviderAccountObject"

  /provideraccounts/{userid}:
    get:
      tags:
        - developers
      description: get provideraccount of user
      operationId: provideraccount
      parameters:
        - name: userid
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: successfully query
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProviderAccountObject"

  /values/consumption/hour/lastTimeStamp/{providerAccountId}/{datapointname}:
    get:
      tags:
        - developers
      description: get last timestamp of hour values of provideraccount and datapointname
      operationId: valuesConsumptionHourLastTimeStamp
      parameters:
        - name: providerAccountId
          in: path
          required: true
          schema:
            type: integer
        - name: datapointname
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successfully query
          content:
            application/json:
              schema:
                type: string
                format: date-time
                example: 2021-01-30T08:30:00Z

  /values/consumption/day/lastTimeStamp/{providerAccountId}/{datapointname}:
    get:
      tags:
        - developers
      description: get last timestamp of day values of provideraccount and datapointname
      operationId: valuesConsumptionDayLastTimeStamp
      parameters:
        - name: providerAccountId
          in: path
          required: true
          schema:
            type: integer
        - name: datapointname
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successfully query
          content:
            application/json:
              schema:
                type: string
                format: date-time
                example: 2021-01-30T08:30:00Z

  /values/consumption/month/lastTimeStamp/{providerAccountId}/{datapointname}:
    get:
      tags:
        - developers
      description: get last timestamp of month values of provideraccount and datapointname
      operationId: valuesConsumptionMonthLastTimeStamp
      parameters:
        - name: providerAccountId
          in: path
          required: true
          schema:
            type: integer
        - name: datapointname
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successfully query
          content:
            application/json:
              schema:
                type: string
                format: date-time
                example: 2021-01-30T08:30:00Z

  /values/consumption/year/lastTimeStamp/{providerAccountId}/{datapointname}:
    get:
      tags:
        - developers
      description: get last timestamp of year values of provideraccount and datapointname
      operationId: valuesConsumptionYearLastTimeStamp
      parameters:
        - name: providerAccountId
          in: path
          required: true
          schema:
            type: integer
        - name: datapointname
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successfully query
          content:
            application/json:
              schema:
                type: string
                format: date-time
                example: 2021-01-30T08:30:00Z

  /values/feedin/hour/lastTimeStamp/{providerAccountId}/{datapointname}:
    get:
      tags:
        - developers
      description: get last timestamp of hour values of provideraccount and datapointname
      operationId: valuesFeedinHourLastTimeStamp
      parameters:
        - name: providerAccountId
          in: path
          required: true
          schema:
            type: integer
        - name: datapointname
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successfully query
          content:
            application/json:
              schema:
                type: string
                format: date-time
                example: 2021-01-30T08:30:00Z

  /values/feedin/day/lastTimeStamp/{providerAccountId}/{datapointname}:
    get:
      tags:
        - developers
      description: get last timestamp of day values of provideraccount and datapointname
      operationId: valuesFeedinDayLastTimeStamp
      parameters:
        - name: providerAccountId
          in: path
          required: true
          schema:
            type: integer
        - name: datapointname
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successfully query
          content:
            application/json:
              schema:
                type: string
                format: date-time
                example: 2021-01-30T08:30:00Z

  /values/feedin/month/lastTimeStamp/{providerAccountId}/{datapointname}:
    get:
      tags:
        - developers
      description: get last timestamp of month values of provideraccount and datapointname
      operationId: valuesFeedinMonthLastTimeStamp
      parameters:
        - name: providerAccountId
          in: path
          required: true
          schema:
            type: integer
        - name: datapointname
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successfully query
          content:
            application/json:
              schema:
                type: string
                format: date-time
                example: 2021-01-30T08:30:00Z

  /values/feedin/year/lastTimeStamp/{providerAccountId}/{datapointname}:
    get:
      tags:
        - developers
      description: get last timestamp of year values of provideraccount and datapointname
      operationId: valuesFeedinYearLastTimeStamp
      parameters:
        - name: providerAccountId
          in: path
          required: true
          schema:
            type: integer
        - name: datapointname
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: successfully query
          content:
            application/json:
              schema:
                type: string
                format: date-time
                example: 2021-01-30T08:30:00Z

  /values/consumption/hour:
    post:
      tags:
        - developers
      description: save consumption hour values
      operationId: valuesConsumptionHour
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/TimeValueObject"
        required: true
      responses:
            "200":
              description: successfully saved

  /values/consumption/day:
    post:
      tags:
        - developers
      description: save consumption day values
      operationId: valuesConsumptionDay
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/TimeValueObject"
        required: true
      responses:
            "200":
              description: successfully saved

  /values/consumption/month:
    post:
      tags:
        - developers
      description: save consumption month values
      operationId: valuesConsumptionMonth
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/TimeValueObject"
        required: true
      responses:
            "200":
              description: successfully saved

  /values/consumption/year:
    post:
      tags:
        - developers
      description: save consumption year values
      operationId: valuesConsumptionYear
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/TimeValueObject"
        required: true
      responses:
            "200":
              description: successfully saved

  /values/feedin/hour:
    post:
      tags:
        - developers
      description: save feedin hour values
      operationId: valuesFeedinHour
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/TimeValueObject"
        required: true
      responses:
            "200":
              description: successfully saved

  /values/feedin/day:
    post:
      tags:
        - developers
      description: save feedin day values
      operationId: valuesFeedinDay
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/TimeValueObject"
        required: true
      responses:
            "200":
              description: successfully saved

  /values/feedin/month:
    post:
      tags:
        - developers
      description: save feedin month values
      operationId: valuesFeedinMonth
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/TimeValueObject"
        required: true
      responses:
            "200":
              description: successfully saved

  /values/feedin/year:
    post:
      tags:
        - developers
      description: save feedin year values
      operationId: valuesFeedinYear
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/TimeValueObject"
        required: true
      responses:
            "200":
              description: successfully saved

  /consumption/saveYearValues:
    post:
      tags:
        - developers
      description: save year values in database
      operationId: saveYearValues
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/TimeValueObject"
        required: true
      responses:
        "200":
          description: successfully saved

  /users:
    get:
      tags:
        - developers
      description: get all users
      operationId: users
      responses:
        "200":
          description: successfully query
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/UserObject"
servers:
  - url: https://localhost:8080/api/v1
  - url: http://localhost:8080/api/v1
components:
  schemas:
    UserObject:
      type: object
      properties:
        id:
          type: int
          example: 1
          description: id of user
        name:
          type: string
          example: hugo
          description: username
        firstname:
          type: string
          example: Hugo
          description: first name of user
        surename:
          type: string
          example: Muster
          description: surename of user
        email:
          type: string
          example: a@b.xyz
          description: email address of user

    TimeValueObject:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          example: 2021-01-30T08:30:00Z
          description: timestamp of the value
        datapointname:
          type: string
          example: xyz
          description: name of the datapoint
        providerAccountId:
          type: integer
          example: 1
          description: provider account id
        value:
          type: number
          example: 1.13
          description: diff value since last value
        counterValue:
          type: number
          example: 1.13
          description: counter value of the smart meeter
    ProviderAccountObject:
      type: object
      properties:
        providerName:
          type: string
          example: nb
          description: provider short name
        providerFullName:
          type: string
          example: Netz Burgenland
          description: provider full name
        providerType:
          type: integer
          example: 0
          description: provider type 0=energy provider, 1=inverter
        providerId:
          type: integer
          example: 1
          description: provider id
        providerAccountId:
          type: integer
          example: id
          description: id of provider account
        providerAccountUsername:
          type: string
          example: user
          description: provider account user name
        providerAccountPassword:
          type: string
          example: pass
          description: provider account user password