name: CI pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_maven:
    name: Build java project with Maven
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

  push_to_registry:
    name: Push image to GitHub Container Registry
    runs-on: ubuntu-latest
    needs: build_maven

    steps:
      - uses: actions/checkout@v3
        name: Checkout repository

      - uses: pmorelli92/github-container-registry-build-push@2.0.0
        name: Build and Publish latest container image
        with:
          github-push-secret: ${{ secrets.GITHUB_TOKEN }}
          docker-image-name: fppss-rest-api
          docker-image-tag: latest # optional
          dockerfile-path: ./Dockerfile # optional
          build-context: ./ # optional
